const WishListData = [
    {
        id: 1,
        name: "AFRICAN DESIGNED TOTE LIGHTWEIGHT BAG",
        warranty: true,
        specialsale: false,
        price: "24,999.99",
        shipping: "234.99",
        sold: 15,
        left: 7,
        ratings: "4.5",
        image_url: "../../Images/image3.jpg",
        wishlist: true
    },
    {
        id: 2,
        name: "Mac Book Pro",
        warranty: true,
        specialsale: true,
        price: "624,999.99",
        shipping: "Free",
        sold: 324,
        left: 9,
        ratings: "5.0",
        image_url: "../../Images/image1.jpg",
        wishlist: true
    },
    {
        id: 3,
        name: "Samsung QLED TV",
        warranty: false,
        specialsale: true,
        price: "1,324,999.99",
        shipping: "79.99",
        sold: 2,
        left: 20,
        ratings: "2.8",
        image_url: "../../Images/image1.jpg",
        wishlist: true
    },
    {
        id: 4,
        name: "Samsung QLED TV",
        warranty: false,
        specialsale: true,
        price: "1,324,999.99",
        shipping: "79.99",
        sold: 2,
        left: 7,
        ratings: "2.8",
        image_url: "../../Images/image1.jpg",
        wishlist: true
    },
    {
        id: 5,
        name: "Samsung QLED TV",
        warranty: false,
        specialsale: true,
        price: "1,324,999.99",
        shipping: "79.99",
        sold: 2,
        left: 7,
        ratings: "2.8",
        image_url: "../../Images/image1.jpg",
        wishlist: true
    },
    {
        id: 6,
        name: "African Designed Tote Lightweight Bag",
        warranty: true,
        specialsale: false,
        price: "24,999.99",
        shipping: "234.99",
        sold: 15,
        left: 7,
        ratings: "4.5",
        image_url: "../../Images/image3.jpg",
        wishlist: true
    },
    {
        id: 7,
        name: "Mac Book Pro",
        warranty: true,
        specialsale: true,
        price: "624,999.99",
        shipping: "Free",
        sold: 324,
        left: 7,
        ratings: "5.0",
        image_url: "../../Images/image1.jpg",
        wishlist: true
    },
    {
        id: 8,
        name: "Samsung QLED TV",
        warranty: false,
        specialsale: true,
        price: "1,324,999.99",
        shipping: "79.99",
        sold: 2,
        left: 7,
        ratings: "2.8",
        image_url: "../../Images/image1.jpg",
        wishlist: true
    },
    {
        id: 9,
        name: "Samsung QLED TV",
        warranty: false,
        specialsale: true,
        price: "1,324,999.99",
        shipping: "79.99",
        sold: 2,
        left: 7,
        ratings: "2.8",
        image_url: "../../Images/image1.jpg",
        wishlist: true
    },
    {
        id: 10,
        name: "Samsung QLED TV",
        warranty: false,
        specialsale: true,
        price: "1,324,999.99",
        shipping: "79.99",
        sold: 2,
        left: 7,
        ratings: "2.8",
        image_url: "../../Images/image1.jpg",
        wishlist: true
    }
]

export default WishListData;